export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_VERIFICATION: '/auth/resend-verification',
    REQUEST_PASSWORD_RESET: '/auth/request-password-reset',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    ME: '/users/me',
    UPDATE_ME: '/users/me',
    DELETE_ME: '/users/me',
  },
  CATALOG: {
    PRODUCTS: '/products/catalog',
    CONFIG: '/products/catalog/config',
    SPEC_VALUES: '/products/catalog/spec-values',
    PRICE_RANGE: '/products/catalog/price-range',
    CATEGORY_COUNTS: '/products/catalog/category-counts',
    PRODUCT: (slugOrId: string) => `/products/${slugOrId}` as const,
    RELATED: (slugOrId: string) => `/products/${slugOrId}/related` as const,
    FEATURED: '/products/featured',
  },
  PROJECTS: {
    ACTIVE: '/projects',
    GET: (id: string) => `/projects/${id}` as const,
    ADMIN_LIST: '/projects/admin',
    CREATE: '/projects',
    UPDATE: (id: string) => `/projects/${id}` as const,
    DELETE: (id: string) => `/projects/${id}` as const,
    UPLOAD_IMAGE: (id: string) => `/projects/${id}/image` as const,
  },
  ARTICLES: {
    LIST: '/articles',
    BY_SLUG: (slug: string) => `/articles/${slug}` as const,
    ADMIN_LIST: '/articles/admin',
    ADMIN_BY_ID: (id: string) => `/articles/admin/${id}` as const,
    CREATE: '/articles',
    UPDATE: (id: string) => `/articles/${id}` as const,
    DELETE: (id: string) => `/articles/${id}` as const,
    UPLOAD_COVER: (id: string) => `/articles/${id}/cover` as const,
    UPLOAD_CONTENT_IMAGE: (id: string) => `/articles/${id}/content-image` as const,
    TOGGLE_PUBLISH: (id: string) => `/articles/${id}/toggle-publish` as const,
  },
  ORDERS: {
    CREATE: '/orders',
    ADMIN_LIST: '/orders/admin',
    ADMIN_GET: (id: string) => `/orders/admin/${id}` as const,
    ADMIN_UPDATE_STATUS: (id: string) => `/orders/admin/${id}/status` as const,
    ADMIN_DELETE: (id: string) => `/orders/admin/${id}` as const,
    ADMIN_BULK_STATUS: '/orders/admin/bulk-status',
    ADMIN_ADD_NOTE: (id: string) => `/orders/admin/${id}/notes` as const,
  },
  ADMIN: {
    DASHBOARD_STATS: '/admin/dashboard-stats',
  },
  PRODUCTS: {
    ADMIN_LIST: '/products/admin',
    ADMIN_CATEGORIES: '/products/admin/categories',
    SPEC_SUGGESTIONS: '/products/admin/spec-suggestions',
    UPLOAD_IMAGE: '/products/admin/upload-image',
    DELETE_IMAGE: '/products/admin/delete-image',
    CREATE: '/products',
    UPDATE: (id: string) => `/products/${id}` as const,
    DELETE: (id: string) => `/products/${id}` as const,
    TOGGLE: (id: string) => `/products/${id}/toggle` as const,
    BATCH_TOGGLE: '/products/admin/batch-toggle',
    BATCH_DELETE: '/products/admin/batch-delete',
  },
  INQUIRIES: {
    CREATE: '/inquiries',
    ADMIN_LIST: '/inquiries/admin',
    ADMIN_DELETE: (id: string) => `/inquiries/admin/${id}` as const,
  },
  SITE_SETTINGS: {
    GET: '/site-settings',
    UPDATE: '/site-settings',
  },
} as const;
