export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-email',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  CONTACT: '/contact',
  CATALOG: '/catalog',
  PROJECTS: '/projects',
  PROJECT_DETAIL: (id: string) => `/projects/${id}`,
  BLOG: '/blog',
  BLOG_DETAIL: (slug: string) => `/blog/${slug}`,
  CART: '/cart',
  ADMIN: {
    LOGIN: '/admin',
    DASHBOARD: '/admin/dashboard',
    PRODUCTS_NEW: '/admin/products/new',
    PRODUCTS_EDIT: (id: string) => `/admin/products/${id}/edit`,
    ORDERS: '/admin/orders',
    ORDER_DETAIL: (id: string) => `/admin/orders/${id}`,
    PROJECTS: '/admin/projects',
    PROJECTS_NEW: '/admin/projects/new',
    PROJECTS_EDIT: (id: string) => `/admin/projects/${id}/edit`,
    CATALOG_SETTINGS: '/admin/catalog-settings',
    ARTICLES: '/admin/articles',
    ARTICLES_NEW: '/admin/articles/new',
    ARTICLES_EDIT: (id: string) => `/admin/articles/${id}/edit`,
    INQUIRIES: '/admin/inquiries',
    SITE_SETTINGS: '/admin/site-settings',
  },
} as const;
